try{
    let a;
    console.log(a.length);
    console.log("Hi i am inside try block")
} catch(e){
    console.log("Hi i am inside catch block")
}
console.log("Hi there")